### ISSUE TITLE
problem with certificate and user identity

### ISSUE THREAD

**Issue by jaimeparragamboa** [mParticle/mparticle-android-sdk#350] opened 2023-03-28 17:25 UTC
Hello, we are implementing the mparticle sdk but we have problems with the http certificates that we have and those of mparticle , we always have this error

`Message: java.net.ConnectException: Failed to connect to identity.mparticle.com/0.0.0.0:443`

this is my code
``` kotlin

val apiResult = instance!!.Identity().login(identityRequest)

apiResult.addFailureListener {
   Log.e("mParticle setProfile addFailureListener", "error $it") // Log print error connection
}
```

when we have the certificate we send some events but they are not seen in the mparticle dashboard

events send code 

``` kotlin
val mParticleEvent = MPEvent.Builder(event.name)
            .eventType(convertEventType(event.eventType))
            .customAttributes(eventData)
            .build()
MParticle.getInstance()?.logEvent(mParticleEvent)
```

the sdk gives us this log

```
03-28 12:16:32.773  9555  9555 D mParticle: Logged event -
03-28 12:16:32.773  9555  9555 D mParticle: Event name: test_event
03-28 12:16:32.773  9555  9555 D mParticle: type: Navigation
03-28 12:16:33.183  9555 10225 D mParticle: Successfully collected Google Play Store Advertising ID.
```

but they do not appear in the mparticle dashboard.

**when we do not have the certificate active, they are sent normally**

i use retrofit to http requeste

**Comment by samdozor** [comment] 2023-06-30 20:23
Hi @jaimeparragamboa is this still an issue for you? IF so, can you clarify how the issue is presenting? When you say you "have the certificate active", do you mean when you are proxying the SDK? If so, you are running up against the SDKs certificate pinning which is there to prevent MITM style attack. You can disable it while in development using the `NetworkOptions` object.

As it's been a while since this was opened, I'm going to close this for now but please let us know if this is still an issue.

**Closed by samdozor** 2023-06-30 20:23 UTC
