### ISSUE TITLE
migrate to AndroidX from support lib

### ISSUE THREAD

**Issue by brianPlummer** [mParticle/mparticle-android-sdk#55] opened 2020-08-18 00:33 UTC
We aren't able to turn off jetifier due to `com.mparticle:android-appboy-kit:5.14.10` and `com.mparticle:android-appsflyer-kit:5.14.10` use of support libraries.  Please consider migrating to androidX.  

Check out this great [article](https://adambennett.dev/2020/08/disabling-jetifier/)

**Comment by GrahamBorland** [comment] 2020-11-26 11:49
Looks like a duplicate of #51

**Comment by willpassidomo** [comment] 2021-01-05 03:11
Apologies for the wait. AndroidX support as of [v5.15.0](https://github.com/mParticle/mparticle-android-sdk/releases/tag/v5.15.0)

**Closed by willpassidomo** 2021-01-05 03:11 UTC
