### ISSUE TITLE
Branch Metrics Kit - App Links are not working

### ISSUE THREAD

**Issue by yuliya-tarasenko** [mParticle/mparticle-android-sdk#9] opened 2016-06-10 11:50 UTC
Hi,
The Branch Metrics allows to enable App Links (starting with API level 23). 
When I enable deep linking with their SDK it works well and I get the correct data:

```
{"+is_first_session":false,"+clicked_branch_link":true,
"+match_guaranteed":true,"$marketing_title":"Test",
"$one_time_use":"","page":"page1",
"~campaign":"Test","~channel":"Email","~creation_source":"Dashboard","~feature":"marketing",
"~id":"..","~marketing":true,"+click_timestamp":1465557985}
```

But when I use:

```
MParticle.getInstance().checkForDeepLink(new DeepLinkListener() {
            @Override
            public void onResult(DeepLinkResult result) {
            }

            @Override
            public void onError(DeepLinkError error) {
            }
        });
```

I get not the full data:

{"+is_first_session":false,"+clicked_branch_link":false}

Can you please say what can be wrong?

**Comment by samdozor** [comment] 2016-06-10 13:36
Hi @yuliya-tarasenko - the data you provided comes directly from the Branch SDK (`{"+is_first_session":false,"+clicked_branch_link":false}`), indicating that the Branch Metrics SDK (via our Branch Metrics Kit integration) was successfully initialized and then determined that this app-open was not immediately proceeded by a link-click. Please make sure that you're using the correct Android Branch dev/API key for your development build. In mParticle, you can configure integrations with a development and a production key - I would expect the above result if you're not using your dev key.

Also, please reach out to your mParticle customer support team rep, and we'd be happy to debug this with you.

**Comment by yuliya-tarasenko** [comment] 2016-06-10 14:28
@samdozor Thank you for the response. Sorry, maybe I described not exactly. The simple deep links (via browser) are working for me with mParticle. 
But I mean direct links to the app (https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/README.md#leverage-android-app-links-for-deep-linking) - this is not working.

**Comment by samdozor** [comment] 2016-06-10 14:55
Hey @yuliya-tarasenko thanks for the clarification! Our engineering team will take look. Can you also shoot an email to support@mparticle.com? Thanks!

**Comment by samdozor** [comment] 2017-01-31 21:34
This should have been resolved for a while - closing the ticket. Please re-open if you're still experience an issue.

**Closed by samdozor** 2017-01-31 21:34 UTC

**Comment by AlexZvonik** [comment] 2017-07-12 06:51
The issue is still reproducible on version 4.15.0
The only difference is that i can reproduce this problem when starting my app from the scratch.
When i'm opening my app while it's exists in the recents - everything works well.
