### ISSUE TITLE
Proguard issue as of 5.9.9

### ISSUE THREAD

**Issue by mateot1** [mParticle/mparticle-android-sdk#37] opened 2019-09-17 19:36 UTC
Trying to update our sdk dependency version from 5.9.5 and it seems that starting with 5.9.9 we get a `java.lang.NoClassDefFoundError` when initializing the sdk (`Mparticle.start` method). With the normal sdk (even trying to keep everything like you suggest in your `consumer-proguard.pro` file) the missing class is obfuscated - either `com.mparticle.internal.i` or `com.mparticle.internal.Q`, when trying the AAR, it is `org.aspectj.runtime.reflect.Factory`, but still crashes when trying to keep classes from `org.aspect.runtime.**`. 

Probably not an issue for us to remain at 5.9.8 for the moment, but any tips would be welcome. Thanks.

**Comment by willpassidomo** [comment] 2019-09-18 15:30
Hey @mateot1 thanks for bringing this issue to our attention. I was able to reproduce this issue on devices with API level < 21, and multidex enabled. Have you seen this behavior outside of those parameters?

I did notice that the missing classes are present in the APK, so I am going to look more into why they are not found on the dex file

Thanks!

**Comment by willpassidomo** [comment] 2019-09-18 16:22
@mateot1 I found 2 potential issues that could be fixed to resolve this issue
1) make sure you Application class is extening `MultiDexApplication` (not `Application`)
2) if that doesn't work, add a multidex keep file.
    - in `build.gradle`, add 
```
android {
    defaultConfig {
        ...
        multiDexKeepProguard file('multidex-keep.pro')
        ....
    }
}
```

    - add a file, `multidex-keep.pro` to the root directory of your module, which contains the line:
```
-keep class com.mparticle.** { *; }
```

This second step will instruct the build tools to keep all mparticle class in the primary dex file

Let me know if either of these works or doesn't work, best of luck!

**Comment by mateot1** [comment] 2019-09-18 16:39
We do indeed have multidex enabled and minSdkVersion < 21, though the crash still happens on devices > 21. We are extending `MultiDexApplication` and unfortunately I am still seeing the crash after trying to add the line to the multiDexKeepProguard file (also tried `-keep class org.aspectj.runtime.** { *; }` there for the AAR again for what it's worth) .

**Comment by willpassidomo** [comment] 2019-09-18 17:04
Would you be willing to share some of the source code? That would help narrow it down

**Comment by mateot1** [comment] 2019-10-01 17:47
Not sure if that's possible 😅 sorry, I know it's hard to reproduce otherwise. Don't think I've found any more clues yet, will let you know if anything changes. At first I thought it might be related to this issue I came across: https://issuetracker.google.com/issues/135210786 but unfortunately forcing a newer R8 version didn't fix it - there are some other open issues related to R8 with gradle 3.5.0, hopefully related to one of those I guess.

**Comment by willpassidomo** [comment] 2019-10-01 17:51
No problem, thanks for the feedback! I'm going to close this in the meantime since it seems to be related to the build tools rather than the SDK itself. I've personally experienced some odd behavior with the new build tools and 5x Gradle versions, I hope and expect these to smooth out over time. Thanks again @mateot1 !

**Closed by willpassidomo** 2019-10-01 17:51 UTC
